
//TYPE 
export const FETCHING_TYPE = 'FETCHING_TYPE';
export const FETCHING_TYPE_SUCCESS = 'FETCHING_TYPE_SUCCESS';
export const FETCHING_TYPE_FAILURE = 'FETCHING_TYPE_FAILURE';


//EVENT
export const FETCHING_EVENT = 'FETCHING_EVENT';
export const FETCHING_EVENT_SUCCESS = 'FETCHING_EVENT_SUCCESS';
export const FETCHING_EVENT_FAILURE = 'FETCHING_EVENT_FAILURE';

// GET EVENT LOCAL
export const FETCH_EVENT_LOCAL = 'FETCH_EVENT_LOCAL';
export const FETCH_EVENT_LOCAL_SUCCESS = 'FETCH_EVENT_LOCAL_SUCCESS';
export const FETCH_EVENT_LOCAL_FAILURE = 'FETCH_EVENT_LOCAL_FAILURE';

//FETCH EVENT MORE

export const FETCHING_MORE_EVENT = 'FETCHING_MORE_EVENT';
export const FETCHING_MORE_EVENT_SUCCESS = 'FETCHING_MORE_EVENT_SUCCESS';
export const FETCHING_MORE_EVENT_FAILURE = 'FETCHING_MORE_EVENT_FAILURE';

// FETCH EVENT MORE LOCAL

export const FETCH_MORE_EVENT_LOCAL = 'FETCH_MORE_EVENT_LOCAL';
export const FETCH_MORE_EVENT_LOCAL_SUCCESS = 'FETCH_MORE_EVENT_LOCAL_SUCCESS';
export const FETCH_MORE_EVENT_LOCAL_FAILURE = 'FETCH_MORE_EVENT_LOCAL_FAILURE';

//Attachment
export const FETCH_ATTACHMENT = 'FETCHING_ATTACHMENT';
export const FETCH_ATTACHMENT_SUCCESS = 'FETCHING_ATTACHMENT_SUCCESS';
export const FETCH_ATTACHMENT_FAILURE = 'FETCHING_ATTACHMENT_FAILURE';


//GET TYPE ID
export const GET_TYPE_ID = 'FETCHING_TYPE_ID';
export const GET_TYPE_ID_SUCCESS = 'FETCHING_TYPE_ID_SUCCESS';
export const GET_TYPE_ID_FAILURE = 'FETCHING_TYPE_ID_FAILURE';


//FETCHING TYPE NAME
export const FETCH_TYPE_BY_NAME = 'FETCH_TYPE_BY_NAME';
export const FETCH_TYPE_BY_NAME_SUCCESS = 'FETCH_TYPE_BY_NAME_SUCCESS';
export const FETCH_TYPE_BY_NAME_FAILURE = 'FETCH_TYPE_BY_NAME_FAILURE';


// FETCHING EVENT BY TYPE LOCAL

export const FETCH_EVENT_BY_TYPE_LOCAL = 'FETCH_EVENT_BY_TYPE_LOCAL';
export const FETCH_EVENT_BY_TYPE_LOCAL_SUCCESS = 'FETCH_EVENT_BY_TYPE_LOCAL_SUCCESS';
export const FETCH_EVENT_BY_TYPE_LOCAL_FAILURE = 'FETCH_EVENT_BY_TYPE_LOCAL_FAILURE';

//GET TYPE LOCAL
export const FETCH_TYPE_BY_NAME_LOCAL = 'FETCH_TYPE_BY_NAME_LOCAL';
export const FETCH_TYPE_BY_NAME_LOCAL_SUCCESS = 'FETCH_TYPE_BY_NAME_LOCAL_SUCCESS';
export const FETCH_TYPE_BY_NAME_LOCAL_FAILURE = 'FETCH_TYPE_BY_NAME_LOCAL_FAILURE';

// FETCHTYPE LOREMORE

export const FETCH_TYPE_LOAD_MORE = 'FETCH_TYPE_LOAD_MORE';
export const FETCH_TYPE_LOAD_MORE_SUCCESS = 'FETCH_TYPE_LOAD_MORE_SUCCESS';
export const FETCH_TYPE_LOAD_MORE_FAILURE = 'FETCH_TYPE_LOAD_MORE_FAILURE';


// FETCH MORE EVENT BY TYPE LOCCAL
export const FETCH_MORE_TYPE_BY_NAME_LOCAL = 'FETCH_MORE_TYPE_BY_NAME_LOCAL';
export const FETCH_MORE_TYPE_BY_NAME_LOCAL_SUCCESS = 'FETCH_MORE_TYPE_BY_NAME_LOCAL_SUCCESS';
export const FETCH_MORE_TYPE_BY_NAME_LOCAL_FAILURE = 'FETCH_MORE_TYPE_BY_NAME_LOCAL_FAILURE';


//FETCH iCALENDAR
export const FETCHING_CALENDAR = 'FETCHING_CALENDAR';
export const FETCHING_CALENDAR_SUCCESS = 'FETCHING_CALENDAR_SUCCESS';
export const FETCHING_CALENDAR_FAILURE = 'FETCHING_CALENDAR_FAILURE';


//TABLET
export const GET_EVENT_LIST_SUCCESS = 'GET_EVENT_LIST_SUCCESS';


// ALL STATE
export const GET_ALL_STATE = 'GET_ALL_STATE';

// SAVE TO LOCAL
export const SAVE_TO_LOCAL = 'SAVE_TO_LOCAL';
export const SAVE_TO_LOCAL_SUCESS = 'SAVE_TO_LOCAL_SUCESS';
export const SAVE_TO_LOCAL_FAILURE = 'SAVE_TO_LOCAL_FAILURE';


// CHECK NETWORK

export const CHECK_NETWORK_INFO = 'CHECK_NETWORK_INFO';


// GET TYPE NAME

export const GET_TYPE_NAME = 'GET_TYPE_NAME';
export const GET_TYPE_NAME_SUCCESS = 'GET_TYPE_NAME_SUCCESS';


// GET DATA FILTER

export const GET_DATA_FILTER = 'GET_DATA_FILTER';
